services:
  - type: web
    name: dv-lottery-photo-editor
    env: python
    plan: free
    buildCommand: |-
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
