services:
  - type: web
    name: dv-lottery-photo-editor
    env: python
    plan: free
    buildCommand: |-
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
